/// This is autogenerated code. If you wish to edit this file press Scene Names -> Save scene names in options. 
namespace Homebrew
{
public enum Scenes
{
sceneKernel = 0,
sceneTest = 1,
sceneUI = 2,
test = 3
}
public static class ExtScenes	{	public static void To(this Scenes s)	{	ProcessingSceneLoad.To((int) s);	}}}
