/// This is autogenerated code. If you wish to edit this file press Scene Names -> Save scene names in options. 
namespace Homebrew
{
[System.Flags]
public enum Scenes
{
sceneLevel1 = 0,
sceneLv1Room6 = 1,
sceneKernel = 2,
sceneCamera = 3,
sceneLv1Room5 = 4
}
public static class ExtScenes	{	public static void To(this Scenes s)	{	ProcessingSceneLoad.To((int) s);	}}}
