/// This is autogenerated code. If you wish to edit this file press Scene Names -> Save scene names in options. 
namespace Homebrew
{
[System.Flags]
public enum Scenes
{
sceneGame = 0,
sceneCamera = 1,
sceneKernel = 2
}
public static class ExtScenes	{	public static void To(this Scenes s)	{	ProcessingSceneLoad.To((int) s);	}}}
